### ISSUE TITLE
Ionic Deploy Plugin Error on Android 4.3 or older

### ISSUE THREAD

**Issue by MikeLallemont** [driftyco/ionic-service-deploy#27] opened 2015-07-07 15:38 UTC
When running our app on Android devices we receive this error:

java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets

**Comment by ericb** [comment] 2015-07-13 12:07
What version of Android?

**Comment by ericb** [comment] 2015-07-13 13:51
Nevermind, i didn't see it in the title initially. :)

**Comment by ericb** [comment] 2015-07-13 15:48
This is a duplicate of driftyco/ionic-plugins-deploy/issues/19. Please follow that issue for updates.

**Closed as completed by ericb** 2015-07-13 15:48 UTC
Labels: duplicate
